all: index.html

index.html: 10_intro.md 20_virtual.md 25_vm_data.md 30_vm_op.md 35_vm_files.md 40_conclusion.md
	pandoc -s 10_intro.md 20_virtual.md 25_vm_data.md 30_vm_op.md 35_vm_files.md 40_conclusion.md --toc -o index.html
